name: legal-dashboard
services:
  - name: legal-dashboard
    source_dir: /
    github:
      repo: your-username/legal-dashboard
      branch: main
    dockerfile_path: Dockerfile
    environment_slug: docker
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
    envs:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PORT
        value: "8000"
    routes:
      - path: /
    alerts:
      - rule: DEPLOYMENT_FAILED
      - rule: DOMAIN_FAILED
    cors:
      allow_origins:
        - "*"
      allow_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allow_headers:
        - "*"
      expose_headers:
        - "*"
      max_age: 86400