name: 🚀 Deploy Legal Dashboard (LocalTunnel)

on:
  workflow_dispatch:

jobs:
  deploy-demo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install LocalTunnel
      run: npm install -g localtunnel
    
    - name: Setup Dependencies  
      run: |
        cd frontend && npm install
        cd ../backend && npm install
    
    - name: Deploy with LocalTunnel
      run: |
        # Start backend
        cd backend
        node server.js &
        BACKEND_PID=$!
        cd ..
        sleep 8
        
        # Build and start frontend
        cd frontend
        npm run build
        npm run preview --port 5173 &
        FRONTEND_PID=$!
        cd ..
        sleep 10
        
        # Create localtunnel
        lt --port 5173 --subdomain legal-dashboard-$(date +%s) > tunnel.log &
        LT_PID=$!
        sleep 10
        
        # Get the public URL
        TUNNEL_URL=$(grep -o 'https://legal-dashboard-[0-9]*\.loca\.lt' tunnel.log | head -1)
        
        echo "🌐 Your Legal Dashboard is LIVE at: $TUNNEL_URL"
        
        # Create demo report
        cat > localtunnel-demo-report.html << EOF
        <!DOCTYPE html>
        <html>
        <head>
            <title>🎬 Legal Dashboard Demo (LocalTunnel)</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
                .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; }
                .live-url { background: #28a745; color: white; padding: 20px; border-radius: 8px; text-align: center; margin: 20px 0; }
                .live-url a { color: white; text-decoration: none; font-size: 18px; font-weight: bold; }
                .demo-frame { width: 100%; height: 800px; border: 2px solid #ddd; border-radius: 8px; }
                h1 { color: #333; text-align: center; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>🎬 Legal Dashboard Live Demo (LocalTunnel)</h1>
                
                <div class="live-url">
                    <p>🌐 <strong>LIVE DASHBOARD URL:</strong></p>
                    <a href="$TUNNEL_URL" target="_blank">$TUNNEL_URL</a>
                    <p><small>⏰ Available for 60 minutes</small></p>
                </div>
                
                <h2>📱 Live Dashboard:</h2>
                <iframe src="$TUNNEL_URL" class="demo-frame"></iframe>
                
                <p style="text-align: center; margin-top: 20px;">
                    <strong>Note:</strong> LocalTunnel may show a warning page first - just click "Continue" to access your dashboard!
                </p>
            </div>
        </body>
        </html>
        EOF
        
        # Keep alive for 60 minutes
        echo "⏰ Keeping demo alive for 60 minutes..."
        for i in {1..60}; do
            echo "⏱️ Demo running... ${i}/60 minutes"
            sleep 60
        done
        
        # Cleanup
        kill $BACKEND_PID $FRONTEND_PID $LT_PID 2>/dev/null || true
    
    - uses: actions/upload-artifact@v4
      with:
        name: localtunnel-demo
        path: |
          localtunnel-demo-report.html
          tunnel.log