name: 📄 Deploy GitHub Pages (Static Frontend)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install and build frontend
        run: |
          set -euxo pipefail
          cd frontend
          npm install
          NODE_ENV=production npm run build
          cd ..

      - name: Create demo landing page
        run: |
          set -euo pipefail
          mkdir -p frontend/dist
          cat > frontend/dist/demo-landing-page.html << 'EOF'
          <!DOCTYPE html>
          <html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>Legal Dashboard – Demo Landing</title>
          <style>body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,Noto Sans,sans-serif;margin:0;background:#f5f7fb} .wrap{max-width:1100px;margin:32px auto;background:#fff;border-radius:12px;box-shadow:0 10px 30px rgba(0,0,0,.06);overflow:hidden} .head{background:#1f2937;color:#fff;padding:24px;text-align:center} .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px;padding:20px} .card{background:#f9fafb;border-radius:10px;padding:16px;border-left:4px solid #2563eb} .btn{display:inline-block;padding:10px 18px;background:#2563eb;color:#fff;text-decoration:none;border-radius:8px;font-weight:700} .center{text-align:center;margin:16px 0}</style></head>
          <body><div class="wrap"><div class="head"><h1>Legal Dashboard</h1><p>Static frontend via GitHub Pages</p></div>
          <div class="center"><a class="btn" href="./index.html">Open Frontend</a> <a class="btn" href="https://github.com/REPO_PLACEHOLDER/actions">Run Live Demo</a></div>
          <div class="grid">
            <div class="card"><h3>Static Frontend</h3><div>UI and components are available.</div><div>Backend calls require live demo or local dev.</div></div>
            <div class="card"><h3>Run Live Demo</h3><div>Go to GitHub Actions and run ngrok or LocalTunnel demo.</div><div>You'll get a public URL in minutes.</div></div>
            <div class="card"><h3>Local Development</h3><div>Clone repo and run <code>./simple-demo.sh</code>.</div><div>Access at http://localhost:5173</div></div>
            <div class="card"><h3>Docs & Support</h3><div>See docs in the repository for setup and troubleshooting.</div></div>
          </div>
          <div class="center" style="color:#6b7280;padding:16px;border-top:1px solid #e5e7eb">Last updated: DATE_PLACEHOLDER</div>
          </div></body></html>
          EOF
          sed -i "s|REPO_PLACEHOLDER|${{ github.repository }}|g" frontend/dist/demo-landing-page.html
          sed -i "s|DATE_PLACEHOLDER|$(date -u +"%Y-%m-%d %H:%M UTC")|g" frontend/dist/demo-landing-page.html

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4