name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 24498743
          password: Ll12345678@

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            24498743/legal-dashboard:latest
            24498743/legal-dashboard:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify push success
        run: |
          echo "✅ Docker image successfully pushed to Docker Hub!"
          echo "📦 Image: 24498743/legal-dashboard:latest"
          echo "📦 Image: 24498743/legal-dashboard:${{ github.sha }}"
          echo "🔗 View at: https://hub.docker.com/r/24498743/legal-dashboard"